name: Build and Test
 
on:
  pull_request:
    branches:
      - main
  push:
    branches:    
    - main 

  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: latest
        run_install: |
          - recursive: true
            args: [--no-frozen-lockfile]
          - args: [--global, aws-cdk]

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.8.1
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true

    - name: Build (front)
      working-directory: front
      env:
        NEXT_PUBLIC_API_URL: http://localhost:3000/
      run: pnpm build
  